args:
  aggr: max
  checkpoint: Anymate/checkpoints
  device: cuda
  epochs: 200
  finetune: true
  gamma: 0.2
  input_normal: false
  logdir: Anymate/logs
  loss: ce
  mode: conn
  resume: ''
  root: Anymate/data
  schedule: []
  start_epoch: 0
  test_batch: 1
  testset: Anymate_test
  train_batch: 16
  trainset: Anymate_train
  test_freq: 10

optimizer: 
  weight_decay: 1.0e-05
  lr: 0.0001
  
model:
  decoder: attendjoints_con_combine
  encoder: bert
  config_path: ./ThirdParty/michelangelo/configs/aligned_shape_latents/shapevae-256.yaml
  ckpt_path: ./ThirdParty/michelangelo/checkpoints/aligned_shape_latents/shapevae-256.ckpt
  load_encoder: ''
  num_joints: 96
  out_channels: 3
  width: 768
  heads: 12
  init_scale: 0.25
  flash: False
  use_checkpoint: False
  qkv_bias: False
  separate: False